config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/thanks", to: "pages#thanks"
  get "/campaign", to: "donations#new"

  resources :donations, except: [:show] do
    patch :trigger, on: :member
  end
  resources :api_tokens, only: [:index, :create, :destroy]

  # GET /api/v1/
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        # Validates api is ok
        get "donaronline/health", to: "donaronline#health"
        get "donaronline/who_i_am", to: "donaronline#who_i_am"
        resources :donations, except: [:new, :edit]
      end
    end
  end
end

app/models/api_token.rb
# == Schema Information
#
# Table name: api_tokens
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  token      :text             not null
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ApiToken < ApplicationRecord
  belongs_to :user
  validates :token, presence: true, uniqueness: true

  before_validation :generate_token, on: :create

  encrypts :token, deterministic: true

  scope :ordered, -> { order( id: :desc ) }

  private

  def generate_token
    self.token = Digest::MD5.hexdigest(SecureRandom.hex)
  end
end

app/controllers/api_tokens_controller.rb
class ApiTokensController < ApplicationController
  def index
    @api_tokens = current_user.api_tokens.ordered
  end

  def create
    @api_token = current_user.api_tokens.create!
    respond_to do |format|
      format.html { redirect_to api_tokens_path, notice: "Token exitosamente generado." }
      format.turbo_stream { flash.now[:notice] = "Token exitosamente generado." }
    end
  end

  def destroy
    @api_token = current_user.api_tokens.find(params[:id])
    if @api_token.destroy
      respond_to do |format|
        format.html { redirect_to api_tokens_path, notice: "Token exitosamente eliminado." }
        format.turbo_stream { flash.now[:notice] = "Token exitosamente eliminado." }
      end
    end
  end
end

app/helpers/api_tokens_helper.rb
module ApiTokensHelper
end

app/views/api_tokens/_api_token.html.erb
<%= turbo_frame_tag api_token do %>
  <div class="d-flex mb-2 px-2 py-1 align-items-center border rounded shadow">
    <div class="col">
      <%= api_token.token %>
    </div>
    <!-- Actions -->
    <div class="col-1 d-flex justify-content-end">
      <%= button_to api_token_path(api_token), method: :delete, data: { turbo_confirm: "Esta seguro?" }, class: "btn btn-danger" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
      </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/api_tokens/create.turbo_stream.erb
<!-- Updates api_tokens list -->
<%= turbo_stream.prepend "api_tokens", @api_token %>

<!-- Flash messages helper -->
<%= render_turbo_stream_flash_messages %>

app/views/api_tokens/destroy.turbo_stream.erb
<!-- Updates api_tokens list -->
<%= turbo_stream.remove @api_token %>

<!-- Flash messages helper -->
<%= render_turbo_stream_flash_messages %>

app/views/api_tokens/index.html.erb
<div class="container">
  <div class="header d-flex align-items-center justify-content-between">
    <h1>Api tokens</h1>
    <%= button_to "Generar token", api_tokens_path, method: :post, class: "btn btn-success" %>
  </div>
  <%= turbo_frame_tag "api_tokens" do %>
    <%= render @api_tokens %>
  <% end %>
</div>