config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/thanks", to: "pages#thanks"
  get "/campaign", to: "donations#new"

  resources :donations, except: [:show] do
    patch :trigger, on: :member
  end
  resources :api_tokens, only: [:index, :create, :destroy]

  # GET /api/v1/
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        # Validates api is ok
        get "donaronline/health", to: "donaronline#health"
        get "donaronline/who_i_am", to: "donaronline#who_i_am"
        resources :donations, except: [:new, :edit]
      end
    end
  end
end

app/models/donation.rb
# == Schema Information
#
# Table name: donations
#
#  id           :bigint           not null, primary key
#  first_name   :string           not null
#  last_name    :string           not null
#  email        :string           not null
#  birth_date   :date             not null
#  phone_number :string           not null
#  options      :hstore
#  status       :string
#  amount       :decimal(10, 2)   not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

# Donation.create!(first_name: "Yeiner", last_name: "Carajal Quina", email: "yeiner@carvajal.com", birth_date: "04/04/1993", phone_numb
# er: "1234567", amount: 100000)

class Donation < ApplicationRecord
  include AASM

  has_one :card, dependent: :destroy, inverse_of: :donation

  validates :first_name, :last_name, :email, :birth_date, :phone_number, :amount, presence: true
  validates :phone_number, numericality: true
  validates :amount, numericality: { greater_than: 0 }
  validates :card, presence: true
  # validates :has_valid_card, on: :create

  accepts_nested_attributes_for :card, reject_if: :all_blank, allow_destroy: true

  # Query filters
  scope :ordered, -> { order(id: :desc) }
  scope :filter_by_date, ->(start_date, end_date) { where("donations.created_at >= ? AND donations.created_at <= ?", start_date, end_date) }

  # On CRUD actions updates donation index
  broadcasts_to ->(donation) { "donations" }, inserts_by: :prepend

  def donor
    "#{first_name} #{last_name}"
  end

  # State machine to manage donation status
  aasm column: :status do
    state :recibida, initial: true
    state :aprobada, :rechazada, :cobrada

    event :aprobar do
      transitions from: [:recibida, :rechazada], to: :aprobada
    end

    event :rechazar do
      transitions from: :recibida, to: :rechazada
    end

    event :cobrar do
      transitions from: :aprobada, to: :cobrada
    end
  end


  private

  def has_valid_card
    if cards.count != 12
      errors.add(:card_number, "must have 12 digits")
    end
  end
end

app/controllers/api/v1/donations_controller.rb
class Api::V1::DonationsController < Api::V1::AuthenticatedController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  before_action :set_client_ip, :set_user_agent, only: [:create]

  def index
    # If there is not filter date params show donations
    # curl -X GET "localhost:3000/api/v1/donations" -H "Authorization: Bearer TOKEN"
    @donations = Donation.where(nil).includes(:card).ordered
    # Else show donations between start_date and end_date
    # curl -X GET "localhost:3000/api/v1/donations?start_date=AAAA-MM-DD&end_date=AAAA-MM-DD" -H "Authorization: Bearer TOKEN"
    if params[:start_date].present? and params[:end_date].present?
      @donations =  Donation.filter_by_date(
        Date.parse(params[:start_date]).beginning_of_day,
        Date.parse(params[:end_date]).end_of_day
      ).includes(:card).ordered
    end
  end

  # curl -X GET "localhost:3000/api/v1/donations/:id" -H "Authorization: Bearer TOKEN"
  def show
  end

  # curl -X POST "localhost:3000/api/v1/donations" -H 'Content-Type: application/json' -H "Authorization: Bearer TOKEN" -d '{ "donation":{"first_name":"Test", "last_name":"Test", "email":"mail@test.com", "birth_date":"2023-07-03", "phone_number":"123456", "amount":"100000", "card_attributes":{"card_number":"123456789012", "security_code":"123", "expiration_date":"2023-07-28", "card_type":"visa", "document_type":"cc", "document_number":"7654321", "_destroy":"false"}} }'
  def create
    @donation = Donation.new(donation_params)
    # Set ip_address and user_agent options to donation
    @donation.options[:ip_address] = @client_ip
    @donation.options[:user_agent] = @user_agent
    if @donation.save
      render @donation, status: :created
      # Send message to donor email
      DonorMailer.with(donation: @donation).donation_email.deliver_later
    else
      render @donation.errors, status: :unprocessable_entity
    end
  end

  # curl -X PATCH "localhost:3000/api/v1/donations/:id" -H 'Content-Type: application/json' -H "Authorization: Bearer TOKEN" -d '{ "donation":{"first_name":"Andrea Maria","last_name":"Roa","email":"andrea@roa.com","birth_date":"2023-07-03","phone_number":"12345678","options":{"ip_address":"127.0.0.1","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"},"status":null,"amount":"50000.0","card_attributes":{"id":16,"card_number":"","security_code":"123","card_type":"mastercard","document_type":"cc","document_number":"9876543","donation_id":23,"expiration_date":"2023-07-21"}} }'
  def update
    if @donation.update(donation_params)
      render json: { message: "Donacion exitosamente editada." }, status: :ok
    else
      render json: @donation.errors, status: :unprocessable_entity
    end
  end

  # curl -X DELETE http://localhost:3000/api/v1/donations/:id -H "Authorization: Bearer TOKEN"
  def destroy
    if @donation.destroy
      render json: { message: "Donacion exitosamente eliminada." }, status: :ok
    end
  end

  private

  def set_user_agent
    @user_agent = request.user_agent
  end

  def set_client_ip
    @client_ip = request.ip
  end

  def set_donation
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(
      :first_name,
      :last_name,
      :email,
      :birth_date,
      :phone_number,
      :amount,
      card_attributes: [
        :id,
        :_destroy,
        :card_number,
        :security_code,
        :expiration_date,
        :card_type,
        :document_type,
        :document_number,
        :donation_id
      ]
    )
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create ] # Skip authentications to create a donation
  before_action :set_donation, only: [:edit, :update, :destroy, :trigger]
  before_action :set_client_ip, :set_user_agent, only: [:create]

  def index
    # If there is not filter date params show donations
    @donations = Donation.where(nil).ordered
    # Else show donations between start_date and end_date
    if params[:start_date].present? and params[:end_date].present?
      @donations =  Donation.filter_by_date(
        Date.parse(params[:start_date]).beginning_of_day,
        Date.parse(params[:end_date]).end_of_day
      ).includes(:card).ordered
    end
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    # Set ip_address and user_agent options to donation
    @donation.options[:ip_address] = @client_ip
    @donation.options[:user_agent] = @user_agent
    if @donation.save
      # Redirect to thanks page
      redirect_to thanks_path
      # Send message to donor email
      DonorMailer.with(donation: @donation).donation_email.deliver_later
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @donation.update(donation_params)
      respond_to do |format|
        format.html { redirect_to donations_path, notice: "Donacion exitosamente editada." }
        format.turbo_stream { flash.now[:notice] = "Donacion exitosamente editada." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @donation.destroy
      respond_to do |format|
        format.html { redirect_to donations_path, notice: "Donacion exitosamente eliminada." }
        format.turbo_stream { flash.now[:notice] = "Donacion exitosamente eliminada." }
      end
    end
  end

  # Method to change donation status, recieves event param
  def trigger
    if @donation.send "#{params[:event]}!"
      respond_to do |format|
        format.html { redirect_to donations_path, notice: "Estado de la donacion cambiada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Estado de la donacion cambiada exitosamente." }
      end
    else
      redirect_to donations_path, status: :unprocessable_entity, notice: "No se ha podido validar el estado de la donacion."
    end
  end

  private

  def set_user_agent
    @user_agent = request.user_agent
  end

  def set_client_ip
    @client_ip = request.ip
  end

  def set_donation
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(
      :first_name,
      :last_name,
      :email,
      :birth_date,
      :phone_number,
      :amount,
      card_attributes: [
        :id,
        :_destroy,
        :card_number,
        :security_code,
        :expiration_date,
        :card_type,
        :document_type,
        :document_number,
        :donation_id
      ]
    )
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
  # This helper shows the available events for an object with aasm status management
  def available_events_for(account)
    account.aasm.permitted_transitions.map { |t| t[:event] }
  end
end

app/views/donations/_card_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="row">
    <%= f.input :card_number, label: "Numero de tarjeta", placeholder: "12 digitos", class: "form-cotrol", wrapper_html: { class: "col-6" } %>
    <%= f.input :security_code, label: "Codigo de seguridad", placeholder: "3 digitos", class: "form-cotrol", wrapper_html: { class: "col-3" } %>
    <%= f.input :expiration_date, label: "Fecha de expiracion", as: :date, class: "form-control", html5: true, wrapper_html: { class: "col-3" } %>
  </div>
  <div class="row">
    <%= f.input :card_type, as: :select, label: "Tipo de tarjeta", prompt: "Tipo de tarjeta", collection: Card.card_types, class: "form-select", wrapper_html: { class: "col-4" }, value_method: -> (r) { r[0] } %>
    <%= f.input :document_type, as: :select, label: "Tipo de documento", prompt: "Tipo de documento", collection: Card.document_types, class: "form-select", wrapper_html: { class: "col-4" }, value_method: -> (r) { r[0] } %>
    <%= f.input :document_number, label: "Numero de documento", placeholder: '1234567', class: "form-control", wrapper_html: { class: "col-4" } %>
  </div>

  <!-- if action name is edit does not  show remove button -->
  <% if action_name == "new" %>
    <button type="button" data-action="nested-form#remove" class="btn btn-success mb-2">Remover </button>
  <% end %>

  <%= f.hidden_field :_destroy %>
</div>

app/views/donations/_donation.html.erb
<%= turbo_frame_tag donation do %>
  <div class="d-flex border rounded mb-2 p-2 shadow align-items-center">
    <div class="col"><%= l(donation.created_at, format: :short) %></div>
    <div class="col"><%= donation.donor %></div>
    <div class="col"><%= donation.email %></div>
    <div class="col"><%= donation.phone_number %></div>
    <div class="col"><%= number_to_currency( donation.amount, unit: "$", format: "%u %n") %></div>
    <div class="col"><%= donation.status %></div>
    <div class="col d-flex gap-2">

    <!-- This shows available trigger buttons for every acccount -->
    <% if donation.recibida? or donation.aprobada? %>
      <% available_events_for(donation).each do |event| %>
        <%= button_to "#{event}", trigger_donation_path(donation, event: event), method: :patch, data: { turbo_confirm: "Esta seguro?" }, class: "btn btn-success" %>
      <% end %>
    <% end %>
    </div>

    <!-- Actions -->
    <div class="col-1 d-flex justify-content-end gap-2">
      <%= link_to edit_donation_path(donation), data: {turbo_frame: "remote_modal"}, class: "btn btn-success" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
      </svg>
      <% end %>
      <%= button_to donation_path(donation), method: :delete, data: { turbo_confirm: "Esta seguro?" }, class: "btn btn-danger" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
      </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/donations/_form.html.erb
<%= simple_form_for donation, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }, html: { class: "mb-4" } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <%= f.input :first_name, label: "Nombre(s)", placeholder: "Nombre(s)", class: "form-control", input_html: { autofocus: true }, wrapper_html: { class: "col-4" } %>
    <%= f.input :last_name, label: "Apellidos", placeholder: "Apellidos", class: "form-control", wrapper_html: { class: "col-4" } %>
    <%= f.input :email, label: "Correo electronico", placeholder: "mail@example.com", class: "form-control", wrapper_html: { class: "col-4" } %>
  </div>
  <div class="row">
    <%= f.input :birth_date, as: :date, html5: true, class: "form-control", wrapper_html: { class: "col-4" } %>
    <%= f.input :phone_number, label: "Numero de telefono", placeholder: "1234567", class: "form-control", wrapper_html: { class: "col-4" } %>
    <%= f.input :amount, label: "Monto", placeholder: "Cuanto deseas donar?", class: "form-control", wrapper_html: { class: "col-4" } %>
  </div>

  <hr>
  <div class="d-flex justify-content-center mb-4">
    <h4>
      <strong>Datos de la tarjeta de credito</strong>
    </h4>
  </div>

  <!-- Nested fields to credit card -->
  <div>
    <template data-nested-form-target="template">
      <%= f.simple_fields_for :card, Card.new, child_index: 'NEW_RECORD' do |card_fields| %>
      <%= render "card_fields", f: card_fields %>
      <% end %>
    </template>

    <div>
      <%= f.simple_fields_for :card do |card_fields| %>
        <%= render 'card_fields', f: card_fields %>
      <% end %>
      <!-- Inserted credit card will be injected before that target. -->
      <button data-nested-form-target="target" type="button" data-action="nested-form#add" class="btn btn-warning mb-2 empty-state--only-child">Agregar tarjeta</button>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= f.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/donations/destroy.turbo_stream.erb
<!-- updates donation -->
<%= turbo_stream.remove @donation %>

<!-- Flash messages helper -->
<%= render_turbo_stream_flash_messages %>

app/views/donations/edit.html.erb
<div class="container">

  <%= link_to sanitize("&larr; Volver"), :back %>

  <div class="header mt-4">
    <h1>Editar donacion</h1>
  </div>

  <%= turbo_frame_tag "remote_modal" do %>
    <%= render "layouts/modal_content", title: "Editar donacion" do %>
      <%= render 'form', donation: @donation %>
    <% end %>
  <% end %>
</div>

app/views/donations/index.html.erb
<%= turbo_stream_from "donations" %>
<div class="container-fluid">
  <div class="d-flex justify-content-between align-items-center mt-4">
    <h1>Donaciones</h1>
    <!-- Form to search donations between start_date and end_date -->
    <div class="d-flex">
      <%= form_with( url: donations_path, method: :get, data: {turbo_frame: 'donations'}, class: "d-block d-md-flex flex-row gap-2 align-items-center" ) do |form| %>
        Filtrar:
        <div class="col-auto mb-2">
          <%= form.date_field :start_date, class: "form-control" %>
        </div>
        <div class="col-auto mb-2">
          <%= form.date_field :end_date, class: "form-control" %>
        </div>
        <div class="col-auto mb-2">
          <%= form.submit "Buscar", class: "btn btn-warning" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="d-flex border rounded bg-success mb-2 px-2">
    <div class="col">FECHA</div>
    <div class="col">DONANTE</div>
    <div class="col">EMAIL</div>
    <div class="col">TELEFONO</div>
    <div class="col">CANTIDAD</div>
    <div class="col">ESTADO</div>
    <div class="col">GESTION</div>
    <div class="col-1">ACCIONES</div>
  </div>

  <%= turbo_frame_tag "donations" do %>
    <%= render @donations %>
  <% end %>
</div>

app/views/donations/new.html.erb
<div class="container">
  <div class="header mt-4">
    <h1>Nueva donacion</h1>
  </div>

  <%= render 'form', donation: @donation %>
</div>

app/views/donations/trigger.turbo_stream.erb
<!-- Flash messages helper -->
<%= render_turbo_stream_flash_messages %>

app/views/donations/update.turbo_stream.erb
<!-- updates donation -->
<%= turbo_stream.update @donation %>

<!-- Flash messages helper -->
<%= render_turbo_stream_flash_messages %>