config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/thanks", to: "pages#thanks"
  get "/campaign", to: "donations#new"

  resources :donations, except: [:show] do
    patch :trigger, on: :member
  end
  resources :api_tokens, only: [:index, :create, :destroy]

  # GET /api/v1/
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        # Validates api is ok
        get "donaronline/health", to: "donaronline#health"
        get "donaronline/who_i_am", to: "donaronline#who_i_am"
        resources :donations, except: [:new, :edit]
      end
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_modal_content.html.erb
<div class="modal-header">
  <h1 class="modal-title"><%= title %></h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <%= yield %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">DonarOnline</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to_active "Nueva donacion", campaign_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to_active "Donaciones", donations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to_active "Api tokens", api_tokens_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <div class="text-dark me-2">
          <strong>
            <%= current_user.email %>
          </strong>
        </div>
        <%= button_to "Salir", destroy_user_session_path, method: :delete, data: { turbo_confirm: "Quiere cerrar sesion?" }, class: "btn btn-outline-dark" %>
      <% else %>
        <%= button_to "Ingresar", new_user_session_path, method: :get, class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonarOnline</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash container mt-4">
      <%= render 'layouts/flash' %>
    </div>
    <%= yield %>

    <!-- remote modal -->
    <div
      class="modal fade modal-xl"
      id="exampleModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
      data-controller="modal"
      data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <%= turbo_frame_tag "remote_modal" %>
        </div>
      </div>
    </div>
  </body>
</html>